### ISSUE TITLE
Detect Stars

### ISSUE THREAD

**Issue by DangelTheMangel** [DiscoLucas/P3-Project#2]

**Comment by DangelTheMangel** [comment]
Find out what type of dectetion we need

**Comment by DangelTheMangel** [comment]
vi valgte og lave orb detection. Det virker nu men har en fejl med hvis ikke alle variablerne passer til billede kaster ORB klassen en SEHexption så vi skal have fundet ud af hvordan vi finder de rigtige instillinger ud fra et billede

**Comment by HurtigSkelet** [comment]
numberOfFeatures er den mængde features den vil kunne genkende _maksimalt_.

scaleFactor for dummies gør bare hvor hurtigt du vil have det går, høj scale factor er upræcis men hurtig, lav er langsom men præcis. 1 er det laveste den må være.

nLevels er er den mængde af levels der er i ens pyramids. Det mindste level har en linær størrelse. input_image_linear_size/pow(scaleFactor, nlevels - firstLevel)

edgeThreshold er hvordan grænsen til hvor features ikke bliver detected ser ud, og den skal være nogenlunde det samme som patchSize

patchSize er størrelsen af det patch der bliver brugt af BRIEF algoritmen.

firstLevel er det niveau af pyramiden man vil ligge ens source image i. Alle de tidligere levels bliver fyldt med en opskaleret version af ens image.

WTA_K er mængden af points der bliver brugt i hvert element af BRIEF algoritmen.
Normalt er dens value 2, og de to andre mulige værdier er 3 og 4.

ScoreType er den default HARRIS_SCORE som bliver brugt i Harris algoritmen. Man kan også give den FAST_SCORE for at gøre det hurtigere.
Harris algoritmen ranker features.

fastThreshold er 

![Image](https://user-images.githubusercontent.com/103103876/201654189-e1cd71b8-1669-4c87-b267-281dd4f65281.png)

**Comment by DangelTheMangel** [comment]
Prøv at start med     int numberOfFeatures = 500 (Da billeder vi bruger er så store ville jeg forslå som minum at have 1500 punkter),
    float scaleFactor = 1.2f,
    int nLevels = 8,
    int edgeThreshold = 31,
    int firstLevel = 0,
    int WTK_A = 2,
    ORBDetector.ScoreType scoreType = ORBDetector.ScoreType.Harris,
    int patchSize = 31,
    int fastThreshold = 20
[12:07]
Det anbefaler de

**Comment by HurtigSkelet** [comment]
modelKeyPoints er de keypoints der tilhører ens model image.

observedKeyPoints er de keypoints der tilhører ens observed image.

matches er ens matches. Matches, som er et array, har det sådan at hver match skal være er k eller mindre end den samme query descriptor.

mask har at gøre med mask. Det tæller for både input og output.

scaleIncrement er forskellen i skalaen af neighbor hood bins. Det er anbefalet at den er 1.5.

rotationBins er mængden af bins for rotation. Det er anbefalet at den er 20, som betyder at hver bin dækker for 18 grader.

**Comment by DangelTheMangel** [comment]
This issue can be fixed if we solve issue #15

**Comment by DangelTheMangel** [comment]
Billederne er for lyse og det giver fejl hvis vi bare gøre dem lidt mørker hvis de er for lyse så skal alt nok gå!
